QuanLyMAC/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('', include("Quanly.urls")),
    path('admin/', admin.site.urls),
   
]
admin.site.site_header = 'Quan Ly Tram Tron'

Quanly/urls.py
from django.conf.urls import url
from QuanLyMAC import urls
from django.urls import path
from django.urls.resolvers import URLPattern
# from .views import GeneratePDF
from . import views
# from .views import Generated
app_name = 'Quanly'
urlpatterns = [

    path('',views.login_view,name='login'),
    path('logout/',views.logout_view,name='logout'),
    path('home/', views.index, name='index'),   
    path('qlnv/', views.staff, name='staff'),
    path('addstaff/',views.add_staff,name='addstaff'),
    path('qlnv/editsaff/<int:id>/',views.edit_staff,name='editstaff'),
    path('qlnv/delstaff/<int:id>/',views.delete_staff,name='delstaff'),
    path('qlkh/', views.customer, name='customer'), 
    path('addkh/', views.addcustomer, name='addcustomer'), 
    path('od/', views.order, name='order'),
    path('qlkh/<int:id>/', views.editcustomer, name='edit_customer'), 
    path('qlkh/de/<int:id>/', views.deletecustomer, name='delete_customer'),
    #-------------------------------------order--------------------------------
    path('order/',views.add_oder,name='add_order'),
    path('order/edit_order/<int:id>/', views.edit_order, name='edit_order'),
    path('qlkh/delete_order/<int:id>/', views.delete_order, name='delete_order'),
    path('order_detail/', views.order_details,name='order_detail'),
    path('qlkh/view_order_detail/<int:id>', views.view_Order_detail,name='view_order_detail'),
    #------------------------------------orderdetail------------------------------------
    path('add_orderdetail/',views.add_orderdetail,name='add_orderdetail'),
    path('orderdetail/edit_orderdetail/<int:id>/', views.edit_orderdetail,name='edit_orderdetail'),
    path('orderdetail/delete_orderdetails/<int:id>/', views.delete_orderdetails, name='delete_orderdetail'),
    path('orderdetail/add_orderdetail_xl/<int:id>/', views.add_orderdetailxl,name='add_orderdetailxl'),
    path('Shift/',views.Shift,name='Shift'),

    path('Addshift/',views.add_shift,name='Addshift'),
    path('Shift/edit/<int:id>',views.edit_shift,name='edit_shift'),
    path('Shift/delete/<int:id>',views.delete_shift, name='delete_shift'),

    path('Car/',views.Car,name='Car'),
    path('AddCar/',views.add_car,name='AddCar'),
    path('Car/edit/<int:id>',views.edit_car,name='edit_car'),
    path('Car/delete/<int:id>',views.delete_car, name='delete_car'),
     path('daskboard/', views.Daskboard, name = 'dask'),
#     path('savekh/', views.saveCustomer, name='savecustomer'),
#    order
    # -------------------- material --------------------------------------------
    path('Matirial/', views.Material,name='Material'),
    path('add_material/', views.add_material,name='add_material'),
    path('Matirial/edit_material/<int:id>', views.edit_material,name='edit_material'),
    path('Matirial/delete_material/<int:id>',views.delete_material,name='delete_material'),
    #------------------------Concrete --------------------------------------------------------
    path('Concrete/', views.Concrete,name='Concrete'),
    path('add_concrete/', views.add_concrete,name='add_concrete'),
    path('Concrete/view_concret_detail/<int:id>', views.view_concrete_detail,name='view_concrete_detail'),
    path('Concrete/edit_concrete/<int:id>', views.edit_concrete,name='edit_concrete'),
    path('Concrete/delete_concrete/<int:id>',views.delete_concrete,name='delete_concrete'),
    #--------------------------Station----------------------------------------------
    path('Station/', views.Station,name='Station'),
    path('add_station/', views.add_station,name='add_station'),
    path('Station/edit_Station/<int:id>', views.edit_station,name='edit_station'),
    path('Station/delete_station/<int:id>',views.delete_station,name='delete_station'),
    #--------------------------Concrete_detail----------------------------------------------
    path('Concrete_detail/', views.Concrete_detail,name='Concrete_detail'),
    path('add_concrete_detail/', views.add_concrete_detail,name='add_concrete_detail'),
    path('Concrete_detail/edit_concrete_detail/<int:id>', views.edit_concrete_detail,name='edit_concrete_detail'),
    path('Concrete_detail/delete_concrete_detail/<int:id>',views.delete_concrete_detail,name='delete_concrete_detail'),
    #--------------------------Concrete_detail----------------------------------------------
    path('Concrete_detail/pdf/<int:id>',views.printpdf,name='print'),
    # url(r'^Concrete_detail/pdf/$',GeneratePDF.as_view()),
]

Quanly/models.py
from django.db import models
from django.db.models.fields.related import ForeignKey
from django.core.validators import MinValueValidator
#sum

class KhachHang(models.Model):
     HoTen = models.TextField(max_length=40)
     SoDienThoai = models.CharField(max_length=10)
     DiaChi = models.TextField(max_length=100)
     SoCMT = models.TextField(max_length=20)
     def __str__(self):
        return self.HoTen + ' ' + self.SoDienThoai

class VatLieu(models.Model):
    TenVatLieu = models.TextField(max_length=50)
    DonVi = models.TextField(max_length=10)
    def __str__(self):
        return self.TenVatLieu

class MacBetong(models.Model):
    TenMac = models.TextField(max_length=30)
    DoSut = models.PositiveIntegerField(default=0, validators= [MinValueValidator(0)])
    Gia = models.PositiveBigIntegerField(validators= [MinValueValidator(0)])
    vatLieu = models.ManyToManyField(VatLieu, through='ChiTietBeTong')
    def __str__(self):
        return self.TenMac


class ChiTietBeTong(models.Model):
    Mac = models.ForeignKey(MacBetong, on_delete= models.CASCADE)
    vatlieu = models.ForeignKey(VatLieu, on_delete=models.CASCADE)
    KhoiLuong = models.PositiveIntegerField(validators=[MinValueValidator(0)])

    class Meta:
        unique_together = [['Mac', 'vatlieu']]


class CongViec(models.Model):
    TenCongViec = models.TextField(max_length=50)
    def __str__(self):
        return self.TenCongViec

class NhanVien(models.Model):
    HoTen = models.TextField(max_length=40)
    congViec= models.ForeignKey(CongViec, on_delete= models.CASCADE)
    SoDienThoai = models.CharField(max_length=10)
    DiaChi = models.TextField(max_length=100)
    SoCMT = models.TextField(max_length=20)
    def __str__(self) :
        return self.HoTen + ' ' + self.congViec.TenCongViec

class XeBon(models.Model):
    TenXe = models.TextField(max_length=40)
    BienSo = models.TextField(max_length=20)
    nhanVien = models.ForeignKey(NhanVien, on_delete= models.CASCADE)
    TRANG_THAI = (
        ('R', 'Roi'),
        ('B', 'Ban'),
    )
    trangThaiXe = models.CharField(null=True,max_length=5, choices=TRANG_THAI)
    def __str__(self):
        return self.TenXe + ' '+ self.get_trangThaiXe_display()

class CaLamviec(models.Model):
    CA_LAM = (
        ('S', 'Sang'),
        ('D', 'Dem'),   
    )
    nhanvien = models.ManyToManyField(NhanVien)
    soGio = models.IntegerField()
    caLam = models.CharField(max_length=5, choices=CA_LAM )
    def get_epl_values(self):
        ret = ''
        print(self.nhanvien.all())
        # use models.ManyToMany field's all() method to return all the Department objects that this employee belongs to.
        for dept in self.nhanvien.all():
            ret = ret + dept.HoTen + ', '
        # remove the last ',' and return the value.
        return ret[:-2]

class TramTron(models.Model):
    tenTramTron = models.CharField(max_length=30)
    dungTich = models.CharField(max_length=10)
    def __str__(self):
        return self.tenTramTron
# phan quyen nhan vien tram tron
class NhanVienQlyTramTron(models.Manager):
    def get_queryset(self):
        return super().get_queryset().exclude(trangThai = 'dgh')

class NhanVienQlyDh(models.Manager):
    def get_queryset(self):
        return super().get_queryset().exclude(trangThai = 'xl')


class Donhang(models.Model):
    TRANG_THAI = (
        ('cxl', 'Chua xu li'),
        ('xl', 'da xu li'), 
        ('dgh', 'da giao hang'), 
    )
    khachHang = models.ForeignKey(KhachHang, on_delete= models.CASCADE)
    tramTron = models.ForeignKey(TramTron,on_delete= models.CASCADE)
    mac = models.ForeignKey(MacBetong, on_delete= models.CASCADE)
    soKhoi = models.PositiveIntegerField(validators=[MinValueValidator(0)])
    tongGia = models.PositiveIntegerField(default=0,validators=[MinValueValidator(0)]) #soKhoi * MacBetong.Gia
    ngayTao = models.DateTimeField(auto_now_add=True)
    ngayDo = models.DateTimeField()
    trangThai = models.CharField(max_length=30, choices=TRANG_THAI )
    Xe = models.ManyToManyField(XeBon, through='ChiTietDonHang')
    object = models.Manager()
    nvBanhang = NhanVienQlyDh()
    QLTramTron = NhanVienQlyTramTron()
    def __str__(self):
        return 'DON HANG '+ str(self.id)
    @property
    def diff_d_count(self):
        dt=0
        for dtt in Donhang.object.filter(trangThai = 'dgh'):
            dt = dt + dtt.soKhoi *  dtt.mac.Gia
        return dt
    def Total(self):
        return self.soKhoi * self.mac.Gia
    
# class QuanLyDonHang (models.Model):
#     donHang = models.ForeignKey(Donhang, on_delete=models.CASCADE) 
#     nhanVien = models.ForeignKey(NhanVien)
class ChiTietDonHang (models.Model):
    donHang = models.ForeignKey(Donhang, on_delete=models.CASCADE) 
    xeBon = models.ForeignKey(XeBon,on_delete=models.CASCADE)
    class Meta:
        unique_together = [['donHang', 'xeBon']]

Quanly/forms.py
from django.db import models
from django.db.models import fields
from django.forms import widgets
from django.template.defaulttags import widthratio
from django import forms
import datetime
from django.forms import DateTimeField
from .models import *
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import Group 

class AddCustomer(forms.ModelForm):
     class Meta:
        model =  KhachHang
        fields = ['HoTen', 'SoDienThoai', 'DiaChi', 'SoCMT']

# create user
class UserAddForm(UserCreationForm):
	'''
	Extending UserCreationForm - with email

	'''
	email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder':'eg.edwards@rabotecgroup.com'}))

	class Meta:
		model = User
		fields = ['username','email','password1','password2']
		

	def clean_email(self):
		email = self.cleaned_data['email']
		qry = User.objects.filter(email = email)

		domain_list = ['rabotecgroup.com','rabotecghana.com']
		get_rabotec_domain = email.split('@')[1]#get me whatever after @, eg. gmail.com

		print(get_rabotec_domain in domain_list)

		if qry.exists():
			'''
			True - Queryset exist run validation message here
			'''
			raise forms.ValidationError('email {0} already exists'.format(email))


		elif get_rabotec_domain not in domain_list:
			print('test - not in domain')
			raise forms.ValidationError('email does not contain domain')

		return email
# login
class UserLogin(forms.Form):
	username = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'username'}))
	password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'password'}))


# order

class AddOrder(forms.ModelForm):	
	
	# ngayDo = forms.DateTimeField(required=True, input_formats=["%Y-%m-%dT%H:%M", ])
	# ngayTao = forms.DateTimeField( required=True, input_formats=["%Y-%m-%dT%H:%M", ])
	class Meta:	
		model = Donhang
		fields = ['khachHang','tramTron','mac','soKhoi','ngayDo','trangThai']
		widgets = {
		'ngayDo': forms.DateInput(format=('%d-%m-%Y'), attrs={'firstDay': 1, 'pattern=': '\d{4}-\d{2}-\d{2}', 'lang': 'pl', 'format': 'yyyy-mm-dd', 'type': 'date'}),
		
		}
		
		# fields = '__all__'
        # widgets = {
        #     'my_date': DateInput(attrs={'type': 'date'})
        # }

class AddOrderdh(forms.ModelForm):	
	
	# ngayDo = forms.DateTimeField(required=True, input_formats=["%Y-%m-%dT%H:%M", ])
	# ngayTao = forms.DateTimeField( required=True, input_formats=["%Y-%m-%dT%H:%M", ])
	class Meta:	
		model = Donhang
		# ngayDo = None
		fields = ['khachHang','tramTron','mac','soKhoi','ngayDo','trangThai']
		widgets = {
		
		'ngayDo': forms.DateInput(format=('%d-%m-%Y'), attrs={'firstDay': 1, 'pattern=': '\d{4}-\d{2}-\d{2}', 'lang': 'pl', 'format': 'yyyy-mm-dd', 'type': 'date'}),
		}
		
class AddOrdertt(forms.ModelForm):	
	
	# ngayDo = forms.DateTimeField(required=True, input_formats=["%Y-%m-%dT%H:%M", ])
	# ngayTao = forms.DateTimeField( required=True, input_formats=["%Y-%m-%dT%H:%M", ])
	class Meta:	
		model = Donhang
		
		fields = ['trangThai']
		



class AddStaff(forms.ModelForm):
	class Meta:
		model = NhanVien
		fields = '__all__'

class AddShift(forms.ModelForm):
	class Meta:
		model = CaLamviec
		fields = '__all__'

class AddCar(forms.ModelForm):
	class Meta:
		model = XeBon
		fields = '__all__'



#-------------------------------material--------------------------------
class AddMaterial(forms.ModelForm):
	class Meta:
		model = VatLieu
		fields = '__all__'

class AddStation(forms.ModelForm):
	class Meta:
		model = TramTron
		fields = '__all__'

class AddConcrete(forms.ModelForm):
	class Meta:
		model = MacBetong
		fields = ['TenMac','DoSut','Gia']
class AddConcretedetail(forms.ModelForm):
	class Meta:
		model = ChiTietBeTong
		fields = '__all__'


class AddOrderdetails(forms.ModelForm):
	class Meta:
		model = ChiTietDonHang
		fields = '__all__'
class AddOrderdetailsxl(forms.ModelForm):
	class Meta:
		model = ChiTietDonHang
		fields = ['xeBon']

Quanly/templates/Shift/addShift.html
{% extends 'base.html' %}
{% load crispy_forms_tags %} 
{% block extrahead %}
<style>
    .field-__str__ {
        font-family: Consolas, monospace;
    }
</style>
{% endblock %}
{% block stylesheet %} 

.sec{ border:1px solid yellow; background:red; } 
.form-wrapper{ -webkit-box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2); padding: 2%; background:#fff !important; padding-bottom:5%; } .btn-lg{ padding:8px 30px; } .main-panel > .content { padding: 60px 15px; min-height:
calc(100% - 123px); }
 #override-start{ background:none !important; top: 35% !important; right:13px; color:#000; font-size: 24px;    margin-right: -400px;
    margin-top: -13px; } 
 .alert-warning{ background:#fd7b7b; } 
 .alert-success { background-color: #82b72a; } 
 .alert-success,.alert-warning{ font-size:16px; color:#fff;
} 
.prev-holder .prev-avatar{ border-radius:50%; width:250px; height:250px; -webkit-box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5prgba(0,0,0,0.2); box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12),
0 1px 5px 0 rgba(0,0,0,0.2); }
 input, button, select, optgroup, textarea { margin: 0; font-family: inherit; font-size: inherit; line-height: inherit; width: 100%; height: 42px; margin-bottom: 15px; } 
label {
    display: inline-block;
    margin-bottom: 0.5rem;
    color: black;
    font-weight: bold;
}
{% endblock %} 
{% block content%}
<div class="content-body btn-page">
    <div class="container-fluid">
        <section class="form-wrapper">
            <section class="row">
                <section class="col col-sm-8 offset-sm-2">

                    {% if messages %} {% for message in messages %}
                    <div {% if message.tags %} class="{{ message.tags}}" {% endif %}>
                        {{ message }}
                        <button type="button" class="close" id="override-start" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                    </button>
                    </div>
                    {% endfor %} {% endif %}

                </section>
            </section>

            <section class="row">
            <section class="col-lg-12 col-md-12 col-sm-12 text-right">
                <a href="{% url 'Quanly:Shift' %}"> back </a>
            </section>
                <section class="col-lg-12 col-md-12 col-sm-12 text-center">
                    <h3 class="title-h3">{{title}}</h3>
                </section>
            </section>
            <section class="row">
                <section class="col-lg-12 col-md-12 col-sm-12">
                    <form action="" method="POST" enctype="multipart/form-data">
                        {% csrf_token %} {{form | crispy }}
                        <button type="submit" class="btn btn-primary btn-lg btn-block">Submit</button>
                    </form>
                </section>
            </section>
        </section>
    </div>
</div>

{%endblock%}

Quanly/templates/Shift/add_shift.html
{% extends 'base.html' %}
{% load crispy_forms_tags %} 
{% block extrahead %}
<style>
    .field-__str__ {
        font-family: Consolas, monospace;
    }
</style>
{% endblock %}
{% block stylesheet %} 

.sec{ border:1px solid yellow; background:red; } 
.form-wrapper{ -webkit-box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2); padding: 2%; background:#fff !important; padding-bottom:5%; } .btn-lg{ padding:8px 30px; } .main-panel > .content { padding: 60px 15px; min-height:
calc(100% - 123px); }
 #override-start{ background:none !important; top: 35% !important; right:13px; color:#000; font-size: 24px;    margin-right: -400px;
    margin-top: -13px; } 
 .alert-warning{ background:#fd7b7b; } 
 .alert-success { background-color: #82b72a; } 
 .alert-success,.alert-warning{ font-size:16px; color:#fff;
} 
.prev-holder .prev-avatar{ border-radius:50%; width:250px; height:250px; -webkit-box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5prgba(0,0,0,0.2); box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12),
0 1px 5px 0 rgba(0,0,0,0.2); }
 input, button, select, optgroup, textarea { margin: 0; font-family: inherit; font-size: inherit; line-height: inherit; width: 100%; height: 42px; margin-bottom: 15px; } 
label {
    display: inline-block;
    margin-bottom: 0.5rem;
    color: black;
    font-weight: bold;
}
{% endblock %} 
{% block content%}
<div class="content-body btn-page">
    <div class="container-fluid">
        <section class="form-wrapper">
            <section class="row">
                <section class="col col-sm-8 offset-sm-2">

                    {% if messages %} {% for message in messages %}
                    <div {% if message.tags %} class="{{ message.tags}}" {% endif %}>
                        {{ message }}
                        <button type="button" class="close" id="override-start" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                    </button>
                    </div>
                    {% endfor %} {% endif %}

                </section>
            </section>

            <section class="row">
            <section class="col-lg-12 col-md-12 col-sm-12 text-right">
                <a href="{% url 'Quanly:Shift' %}"> back </a>
            </section>
                <section class="col-lg-12 col-md-12 col-sm-12 text-center">
                    <h3 class="title-h3">{{title}}</h3>
                </section>
            </section>
            <section class="row">
                <section class="col-lg-12 col-md-12 col-sm-12">
                    <form action="" method="POST" enctype="multipart/form-data">
                        {% csrf_token %} {{form | crispy }}
                        {% if title == 'NHAP CA LAM VIEC' %}
                        <button type="submit" class="btn btn-primary btn-lg btn-block">Submit</button>
                        {% else %}
                        <button type="submit" id='edit' class="btn btn-primary btn-lg btn-block">Submit</button>
                        {% endif %}
                        
                    </form>
                </section>
            </section>
        </section>
    </div>
</div>

{%endblock%}

Quanly/templates/Shift/edit_shift.html
{% extends 'base.html' %}
{% load crispy_forms_tags %} 
{% block extrahead %}
<style>
    .field-__str__ {
        font-family: Consolas, monospace;
    }
</style>
{% endblock %}
{% block stylesheet %} 

.sec{ border:1px solid yellow; background:red; } 
.form-wrapper{ -webkit-box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2); padding: 2%; background:#fff !important; padding-bottom:5%; } .btn-lg{ padding:8px 30px; } .main-panel > .content { padding: 60px 15px; min-height:
calc(100% - 123px); }
 #override-start{ background:none !important; top: 35% !important; right:13px; color:#000; font-size: 24px;    margin-right: -400px;
    margin-top: -13px; } 
 .alert-warning{ background:#fd7b7b; } 
 .alert-success { background-color: #82b72a; } 
 .alert-success,.alert-warning{ font-size:16px; color:#fff;
} 
.prev-holder .prev-avatar{ border-radius:50%; width:250px; height:250px; -webkit-box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5prgba(0,0,0,0.2); box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12),
0 1px 5px 0 rgba(0,0,0,0.2); }
 input, button, select, optgroup, textarea { margin: 0; font-family: inherit; font-size: inherit; line-height: inherit; width: 100%; height: 42px; margin-bottom: 15px; } 
label {
    display: inline-block;
    margin-bottom: 0.5rem;
    color: black;
    font-weight: bold;
}
{% endblock %} 
{% block content%}
<div class="content-body btn-page">
    <div class="container-fluid">
        <section class="form-wrapper">
            <section class="row">
                <section class="col col-sm-8 offset-sm-2">

                    {% if messages %} {% for message in messages %}
                    <div {% if message.tags %} class="{{ message.tags}}" {% endif %}>
                        {{ message }}
                        <button type="button" class="close" id="override-start" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                    </button>
                    </div>
                    {% endfor %} {% endif %}

                </section>
            </section>

            <section class="row">
            <section class="col-lg-12 col-md-12 col-sm-12 text-right">
                <a href="{% url 'Quanly:Shift' %}"> back </a>
            </section>
                <section class="col-lg-12 col-md-12 col-sm-12 text-center">
                    <h3 class="title-h3">{{title}}</h3>
                </section>
            </section>
            <section class="row">
                <section class="col-lg-12 col-md-12 col-sm-12">
                    <form action="" method="POST" enctype="multipart/form-data">
                        {% csrf_token %} {{form | crispy }}
                        <button type="submit" id="edit_shift" class="btn btn-primary btn-lg btn-block">Submit</button>
                    </form>
                </section>
            </section>
        </section>
    </div>
</div>

{%endblock%}

Quanly/templates/Shift/shift.html
{% extends 'base.html' %}
{% load auth_extras %}
{% block content %}
<div class="content-body btn-page">
    <div class="container-fluid">
        <div class="row page-titles mx-0">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">{{title}}</h4>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered verticle-middle table-responsive-sm">
                                <thead>
                                    <tr>
                                        <th scope="col">Ca lam</th>
                                        <th scope="col">So gio</th>
                                        <th scope="col">Nhan vien </th>                   
                                        <th scope="col">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                              {% if request.user.is_superuser or request.user|has_group:"Quản lý trạm trộn"%}
                                    {% for ca in Ca %}
                                    <tr>
                                        <td>{{ca.get_caLam_display}}</td>
                                        <td>
                                           {{ca.soGio}}
                                        </td>
                                        <td>{{ ca.get_epl_values }}</td>
                                      
                                        <td>
                                            <span>
                                                <a href="{% url 'Quanly:edit_shift' ca.id %}" class="mr-4" data-toggle="tooltip"
                                                    data-placement="top" title="Edit"><i
                                                        class="fa fa-pencil color-muted"></i> </a>
                                                <a href="{% url 'Quanly:delete_shift' ca.id %}" data-toggle="tooltip"
                                                    data-placement="top" title="Close"><i
                                                        class="fa fa-close color-danger"></i></a>
                                            </span>
                                        </td>
                                    </tr>
                                    {% endfor%}
                                    

                                {% endif %}

                               
                               

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{%endblock%}