QuanLyMAC/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('', include("Quanly.urls")),
    path('admin/', admin.site.urls),
   
]
admin.site.site_header = 'Quan Ly Tram Tron'

Quanly/urls.py
from django.conf.urls import url
from QuanLyMAC import urls
from django.urls import path
from django.urls.resolvers import URLPattern
# from .views import GeneratePDF
from . import views
# from .views import Generated
app_name = 'Quanly'
urlpatterns = [

    path('',views.login_view,name='login'),
    path('logout/',views.logout_view,name='logout'),
    path('home/', views.index, name='index'),   
    path('qlnv/', views.staff, name='staff'),
    path('addstaff/',views.add_staff,name='addstaff'),
    path('qlnv/editsaff/<int:id>/',views.edit_staff,name='editstaff'),
    path('qlnv/delstaff/<int:id>/',views.delete_staff,name='delstaff'),
    path('qlkh/', views.customer, name='customer'), 
    path('addkh/', views.addcustomer, name='addcustomer'), 
    path('od/', views.order, name='order'),
    path('qlkh/<int:id>/', views.editcustomer, name='edit_customer'), 
    path('qlkh/de/<int:id>/', views.deletecustomer, name='delete_customer'),
    #-------------------------------------order--------------------------------
    path('order/',views.add_oder,name='add_order'),
    path('order/edit_order/<int:id>/', views.edit_order, name='edit_order'),
    path('qlkh/delete_order/<int:id>/', views.delete_order, name='delete_order'),
    path('order_detail/', views.order_details,name='order_detail'),
    path('qlkh/view_order_detail/<int:id>', views.view_Order_detail,name='view_order_detail'),
    #------------------------------------orderdetail------------------------------------
    path('add_orderdetail/',views.add_orderdetail,name='add_orderdetail'),
    path('orderdetail/edit_orderdetail/<int:id>/', views.edit_orderdetail,name='edit_orderdetail'),
    path('orderdetail/delete_orderdetails/<int:id>/', views.delete_orderdetails, name='delete_orderdetail'),
    path('orderdetail/add_orderdetail_xl/<int:id>/', views.add_orderdetailxl,name='add_orderdetailxl'),
    path('Shift/',views.Shift,name='Shift'),

    path('Addshift/',views.add_shift,name='Addshift'),
    path('Shift/edit/<int:id>',views.edit_shift,name='edit_shift'),
    path('Shift/delete/<int:id>',views.delete_shift, name='delete_shift'),

    path('Car/',views.Car,name='Car'),
    path('AddCar/',views.add_car,name='AddCar'),
    path('Car/edit/<int:id>',views.edit_car,name='edit_car'),
    path('Car/delete/<int:id>',views.delete_car, name='delete_car'),
     path('daskboard/', views.Daskboard, name = 'dask'),
#     path('savekh/', views.saveCustomer, name='savecustomer'),
#    order
    # -------------------- material --------------------------------------------
    path('Matirial/', views.Material,name='Material'),
    path('add_material/', views.add_material,name='add_material'),
    path('Matirial/edit_material/<int:id>', views.edit_material,name='edit_material'),
    path('Matirial/delete_material/<int:id>',views.delete_material,name='delete_material'),
    #------------------------Concrete --------------------------------------------------------
    path('Concrete/', views.Concrete,name='Concrete'),
    path('add_concrete/', views.add_concrete,name='add_concrete'),
    path('Concrete/view_concret_detail/<int:id>', views.view_concrete_detail,name='view_concrete_detail'),
    path('Concrete/edit_concrete/<int:id>', views.edit_concrete,name='edit_concrete'),
    path('Concrete/delete_concrete/<int:id>',views.delete_concrete,name='delete_concrete'),
    #--------------------------Station----------------------------------------------
    path('Station/', views.Station,name='Station'),
    path('add_station/', views.add_station,name='add_station'),
    path('Station/edit_Station/<int:id>', views.edit_station,name='edit_station'),
    path('Station/delete_station/<int:id>',views.delete_station,name='delete_station'),
    #--------------------------Concrete_detail----------------------------------------------
    path('Concrete_detail/', views.Concrete_detail,name='Concrete_detail'),
    path('add_concrete_detail/', views.add_concrete_detail,name='add_concrete_detail'),
    path('Concrete_detail/edit_concrete_detail/<int:id>', views.edit_concrete_detail,name='edit_concrete_detail'),
    path('Concrete_detail/delete_concrete_detail/<int:id>',views.delete_concrete_detail,name='delete_concrete_detail'),
    #--------------------------Concrete_detail----------------------------------------------
    path('Concrete_detail/pdf/<int:id>',views.printpdf,name='print'),
    # url(r'^Concrete_detail/pdf/$',GeneratePDF.as_view()),
]

Quanly/views.py
from django.db.models.aggregates import Count, Min
from django.http.response import HttpResponse
from django.contrib.auth.models import Group 
from django.shortcuts  import render, redirect,get_list_or_404,get_object_or_404
from .models import *
from django.contrib.auth import authenticate, login, logout
from django.views.generic import DeleteView,View
from .forms import *
from django.contrib import messages
from django.contrib.auth.models import Group,User,UserManager
import datetime
from django.db.models import F
from django.db import connection
from django.utils.dateparse import parse_date
from .utils import render_to_pdf
from django.template.loader import get_template
#------------------------------ Create print pdf file ------------------------------
def printpdf(request,id):
	if not (request.user.is_authenticated or request.user.is_superuser or request.user.is_staff):
		return redirect('/')
	# template = get_template('printpft/print_pdf.html')
	ct_car= get_object_or_404(ChiTietDonHang, id = id)
	# ct_car_obj = ChiTietDonHang.objects.filter(ct_car)
	ct_dh = get_object_or_404(Donhang,id = ct_car.donHang.id)
	# ct_mac = get_object_or_404(Donhang,id = ct_car.donHang)
	concrete = get_object_or_404(MacBetong,id=ct_dh.mac.id)
	CT = ChiTietBeTong.objects.filter(Mac = concrete)

	# arr = ['Lai xe:','Xe:','Tram tron:','Khach hang:','Mac:','So khoi:','Date:']
	context = {
	    'ct_car': ct_car,
		'ct_dh' : ct_dh,
		'CT' :CT,
		'user':request.user.username,
		'bh': get_object_or_404(User,id=3)
	}
	# html = template.render(context)
	# return HttpResponse(html)
	pdf = render_to_pdf('printpft/print_pdf.html', context)
	if pdf:
	    response = HttpResponse(pdf, content_type='application/pdf')
	    filename = "name_%s.pdf" %("12341231")
	    content = "inline; filename=%s" %(filename)
	    # download = request.GET.get("download")
	    # if download:
	    #     content = "attachment; filename='%s'" %(filename)
	    response['Content-Disposition'] = content
	    return response
	return HttpResponse("Not found")
        
# Create your views here.
#------------------------------------MAIN---------------------------
def index(request):
    if not (request.user.is_authenticated or request.user.is_superuser or request.user.is_staff):
        return redirect('/')

    return render(request, 'index.html')

#---------------------------------------CUSTOMER-----------------------
def customer(request):
	if not (request.user.is_authenticated or request.user.is_superuser or request.user.is_staff):
		return redirect('/')
	data = { 'khachhang': KhachHang.objects.all(),'title' : 'QUAN LY KHACH HANG'}
	return render(request, 'customer.html', data)

def addcustomer(request):
    if not (request.user.is_authenticated or request.user.is_superuser or request.user.is_staff):
        return redirect('/')
    else:
        if request.method == 'POST':
            form = AddCustomer(data = request.POST)
            if form.is_valid():
                instance = form.save(commit = False)

                instance.HoTen= request.POST.get('HoTen')
                instance.SoDienThoai = request.POST.get('SoDienThoai')
                instance.DiaChi = request.POST.get('DiaChi')
                instance.SoCMT = request.POST.get('SoCMT')

                instance.save()


                messages.success(request,'customer Successfully Created ',extra_tags = 'alert alert-success alert-dismissible show')
                return redirect('Quanly:addcustomer')

            else:
                messages.error(request,'Error Creating Customer ',extra_tags = 'alert alert-warning alert-dismissible show')
                return redirect('Quanly:addcustomer')

        dataset = dict()
        form = AddCustomer()
        dataset['form'] = form
        dataset['title'] = 'TAO KHACH HANG'
        return render(request,'addCustomer.html',dataset)

def editcustomer(request,id):
	if not (request.user.is_authenticated or request.user.is_superuser or request.user.is_staff):
		return redirect('/')
	customer = get_object_or_404(KhachHang, id = id)
	if request.method == 'POST':
		form = AddCustomer(data = request.POST,instance = customer)
		if form.is_valid():
			instance = form.save(commit = False)
			instance.HoTen= request.POST.get('HoTen')
			instance.SoDienThoai = request.POST.get('SoDienThoai')
			instance.DiaChi = request.POST.get('DiaChi')
			instance.SoCMT = request.POST.get('SoCMT')
			instance.save()
			
			messages.success(request,'Customer Successfully  ',extra_tags = 'alert alert-success alert-dismissible show')
			return redirect('Quanly:addcustomer')
		else:
			messages.error(request,'Error Creating Customer ',extra_tags = 'alert alert-warning alert-dismissible show')
			return redirect('Quanly:addcustomer')
		
	dataset = dict()
	form = AddCustomer(request.POST or None,instance = customer)
	dataset['form'] = form
	dataset['title'] = 'EDIT CUSTOMER'
	return render(request,'addCustomer.html',dataset)

def deletecustomer(request,id):
	if not (request.user.is_authenticated or request.user.is_superuser or request.user.is_staff):
		return redirect('/')
	else:
		get_object_or_404(KhachHang, id = id).delete()
		return redirect('Quanly:customer')

		

# SELECT soKhoi,B.Gia, soKhoi * B.Gia as tong ,tongGia, ngayTao, ngayDo, trangThai, khachHang_id, mac_id, tramTron_id
# FROM Quanly_donhang A join Quanly_macbetong B on A.mac_id = B.id WHERE trangThai = 'xl';
#------------------------------------------------ORDER-----------------------------------------
def order(request):
	if not (request.user.is_authenticated or request.user.is_superuser or request.user.is_staff):
		return redirect('/')
	# query = "SELECT A.id, C.HoTen as tkh, B.TenMac, soKhoi,B.Gia, soKhoi * B.Gia as tong , ngayTao, ngayDo, trangThai FROM Quanly_donhang A join Quanly_macbetong B on A.mac_id = B.id  JOIN Quanly_khachhang C on A.khachHang_id = C.id join Quanly_tramtron E on A.tramTron_id = E.id WHERE trangThai = 'cxl';"
	# query1 = "SELECT A.id, C.HoTen as tkh, B.TenMac, soKhoi,B.Gia, soKhoi * B.Gia as tong , ngayTao, ngayDo, trangThai FROM Quanly_donhang A join Quanly_macbetong B on A.mac_id = B.id  JOIN Quanly_khachhang C on A.khachHang_id = C.id join Quanly_tramtron E on A.tramTron_id = E.id  ;"
	# data = {'donhang': Donhang.object.raw(query),
	# 	'donhang1': Donhang.object.raw(query1),
	# 	'donhangall': Donhang.object.all(),
	# 	'title': 'THONG TIN DON HANG'
	# }
	data = { 'donhang1': Donhang.QLTramTron.all(), 
			'donhang2': Donhang.nvBanhang.all()  ,
			'donhang': Donhang.object.all()}
	return render(request, 'Order/order.html', data)
def delete_order(request,id):
	if not (request.user.is_authenticated or request.user.is_superuser or request.user.is_staff):
		return redirect('/')
	else:
		get_object_or_404(Donhang, id = id).delete()
		return redirect('Quanly:order')
def add_oder(request):
	if not (request.user.is_authenticated or request.user.is_superuser or request.user.is_staff):
		return redirect('/')
	else:
		group = Group.objects.get(name = "Quản lý trạm trộn")
		check = True if group in request.user.groups.all() else False
		group1 = Group.objects.get(name = "Bán hàng")
		check1 = True if group1 in request.user.groups.all() else False

		if request.method == 'POST':
			form = AddOrderdh(data = request.POST) if check1 == True else AddOrdertt(data = request.POST) if check==True else AddOrder(data = request.POST)
			
			if form.is_valid():
				
				instance = form.save(commit = False)
				idcustomer = request.POST.get('khachHang')
				idtram = request.POST.get('tramTron')
				idmac = request.POST.get('mac')
				tramobj = get_object_or_404(TramTron,id = idtram)
				cusobj = get_object_or_404(KhachHang,id = idcustomer)
				macobj = get_object_or_404(MacBetong,id = idmac)
				instance.khachHang = cusobj
				instance.tramTron = tramobj
				instance.mac = macobj
				instance.soKhoi = request.POST.get('soKhoi')
				
				
				# instance.ngayTao = request.POST.get('ngayTao')
				# instance.ngayDo = None
				
				instance.trangThai = request.POST.get('trangThai')
				
				#check status in tt 
				if request.POST.get('trangThai') == 'xl' and not check or request.POST.get('trangThai') == 'dgh' and not check:
					messages.error(request,'Error Creating Customer ',extra_tags = 'alert alert-warning alert-dismissible show')
					return redirect('Quanly:add_order')
				
				else:
					instance.save()
				messages.success(request,'order Successfully Created ',extra_tags = 'alert alert-success alert-dismissible show')
				return redirect('Quanly:add_order')

			else:
				messages.error(request,'Error Creating Customer ',extra_tags = 'alert alert-warning alert-dismissible show')
				return redirect('Quanly:add_order')

		dataset = dict()
		form = AddOrderdh() if check1 == True else AddOrdertt() if check==True else AddOrder()
		dataset['form'] = form
		dataset['title'] = 'TAO DON HANG'
		return render(request,'Order/addOrder.html',dataset)
def edit_order(request,id):
	if not (request.user.is_authenticated or request.user.is_superuser or request.user.is_staff):
		return redirect('/')
	else:
		
		order = get_object_or_404(Donhang,id=id)
		group = Group.objects.get(name = "Quản lý trạm trộn")
		check = True if group in request.user.groups.all() else False
		group1 = Group.objects.get(name = "Bán hàng")
		check1 = True if group1 in request.user.groups.all() else False
		dhcu = order.trangThai
		if request.method == 'POST':
			form = AddOrderdh(data = request.POST,instance = order) if check1 == True else AddOrdertt(data = request.POST,instance = order) if check==True else AddOrder(data = request.POST,instance = order)
			if form.is_valid():
				instance = form.save(commit = False)
				if not check:
					idcustomer = request.POST.get('khachHang')
					idtram = request.POST.get('tramTron')
					idmac = request.POST.get('mac')
					tramobj = get_object_or_404(TramTron,id = idtram)
					cusobj = get_object_or_404(KhachHang,id = idcustomer)
					macobj = get_object_or_404(MacBetong,id = idmac)

Quanly/templates/Car/add_car.html
{% extends 'base.html' %}
{% load crispy_forms_tags %} 
{% block extrahead %}
<style>
    .field-__str__ {
        font-family: Consolas, monospace;
    }
</style>
{% endblock %}
{% block stylesheet %} 

.sec{ border:1px solid yellow; background:red; } 
.form-wrapper{ -webkit-box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2); padding: 2%; background:#fff !important; padding-bottom:5%; } .btn-lg{ padding:8px 30px; } .main-panel > .content { padding: 60px 15px; min-height:
calc(100% - 123px); }
 #override-start{ background:none !important; top: 35% !important; right:13px; color:#000; font-size: 24px;    margin-right: -400px;
    margin-top: -13px; } 
 .alert-warning{ background:#fd7b7b; } 
 .alert-success { background-color: #82b72a; } 
 .alert-success,.alert-warning{ font-size:16px; color:#fff;
} 
.prev-holder .prev-avatar{ border-radius:50%; width:250px; height:250px; -webkit-box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5prgba(0,0,0,0.2); box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12),
0 1px 5px 0 rgba(0,0,0,0.2); }
 input, button, select, optgroup, textarea { margin: 0; font-family: inherit; font-size: inherit; line-height: inherit; width: 100%; height: 42px; margin-bottom: 15px; } 
label {
    display: inline-block;
    margin-bottom: 0.5rem;
    color: black;
    font-weight: bold;
}
{% endblock %} 
{% block content%}
<div class="content-body btn-page">
    <div class="container-fluid">
        <section class="form-wrapper">
            <section class="row">
                <section class="col col-sm-8 offset-sm-2">

                    {% if messages %} {% for message in messages %}
                    <div {% if message.tags %} class="{{ message.tags}}" {% endif %}>
                        {{ message }}
                        <button type="button" class="close" id="override-start" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                    </button>
                    </div>
                    {% endfor %} {% endif %}

                </section>
            </section>

            <section class="row">
            <section class="col-lg-12 col-md-12 col-sm-12 text-right">
                <a href="{% url 'Quanly:Car' %}"> back </a>
            </section>
                <section class="col-lg-12 col-md-12 col-sm-12 text-center">
                    <h3 class="title-h3">{{title}}</h3>
                </section>
            </section>
            <section class="row">
                <section class="col-lg-12 col-md-12 col-sm-12">
                    <form action="" method="POST" enctype="multipart/form-data">
                        {% csrf_token %} {{form | crispy }}
                        {% if title == 'NHAP XE BON' %}
                        <button type="submit" class="btn btn-primary btn-lg btn-block">Submit</button>
                        {% else %}
                        <button type="submit" id = 'edit' class="btn btn-primary btn-lg btn-block">Submit</button>
                        {% endif %}
                        
                    </form>
                </section>
            </section>
        </section>
    </div>
</div>

{%endblock%}

Quanly/templates/Car/car.html
{% extends 'base.html' %}

{% block content %}
<div class="content-body btn-page">
    <div class="container-fluid">
        <div class="row page-titles mx-0">
            <div class="col-lg-12">
            
                <div class="card">
                <section class="col-lg-12 col-md-12 col-sm-12 text-right">
                <a href="{% url 'Quanly:index' %}"> back </a>
            </section>
                    <div class="card-header">
                        <h4 class="card-title">{{title}}</h4>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered verticle-middle table-responsive-sm">
                                <thead>
                                    <tr>
                                        <th scope="col">Ten xe</th>
                                        <th scope="col">Bien so</th>
                                        <th scope="col">Nhan vien Phu trach</th>
                                        <th scope="col">Trang thai xe</th>
                                        <th scope="col">Action</th>
                                        
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for xe in Xe%}
                                    <tr>
                                        <td>{{xe.TenXe}}</td>
                                        <td>
                                           {{xe.BienSo}}
                                        </td>
                                        <td>{{xe.nhanVien.HoTen}}</td>
                                        <td>{{xe.get_trangThaiXe_display}}</td>
                                         <td>
                                            <span>
                                                <a href="{% url 'Quanly:edit_car' xe.id %}" class="mr-4" data-toggle="tooltip"
                                                    data-placement="top" title="Edit"><i
                                                        class="fa fa-pencil color-muted"></i> </a>
                                                <a href="{% url 'Quanly:delete_car' xe.id %}" class=""data-toggle="tooltip"
                                                    data-placement="top" title="Close"><i
                                                        class="fa fa-close color-danger"></i></a>
                                            </span>
                                        </td>
                                        <!-- <td>
                                            
                                           
                                        </td> -->
                                    </tr>
                                    {% endfor%}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{%endblock%}